### ISSUE TITLE
create an `Add Chart` command if there is a `charts/myapp/requirements.yaml` file 

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/vscode-jx-tools#28]
if a project has a chart at `charts/myapp/requirements.yaml`  it would be awesome to have an `Add Chart` command that:

* prompted to user to search for charts via text search (like `helm search`) and displayed the results
* if a chart is selected to be added, it then finds the chart repository URL, app name and version and adds the following code to the `charts/myapp/requirements.yaml` file:

```yaml
- name: mychosenchart
  repository: https://some.repo.com
  version: 1.2.3
```
